from typing import List, Optional, Literal
from pydantic import BaseModel, Field, field_validator

ClauseCategory = Literal[
    "Liability",
    "Payment",
    "Intellectual Property",
    "Termination",
    "Obligations",
    "Boilerplate",
    "Confidentiality",
    "Governing Law",
]

AttentionLevel = Literal["high", "moderate", "standard"]


class RawFindingOutput(BaseModel):
    """Raw clause finding generated by LLM specifying source_chunk_id for grounding."""
    category: ClauseCategory = Field(..., description="Legal category of the clause")
    attention_level: AttentionLevel = Field(..., description="Assessed attention level (high, moderate, standard)")
    title: str = Field(..., description="Short descriptive heading for the finding")
    plain_english: str = Field(..., description="Clear explanation in plain English (8th-grade level)")
    why_it_matters: str = Field(..., description="Practical business or legal implication for the user")
    source_chunk_id: str = Field(..., description="Exact ID of the document chunk where clause originated, e.g. chunk-p1-002")

    @field_validator("category", mode="before")
    @classmethod
    def normalize_category(cls, v: str) -> str:
        if not isinstance(v, str):
            return "Obligations"
        v_low = v.strip().lower()
        if "liab" in v_low or "indemn" in v_low:
            return "Liability"
        if "pay" in v_low or "fee" in v_low or "comp" in v_low or "price" in v_low or "bill" in v_low:
            return "Payment"
        if "intellect" in v_low or "ip" in v_low or "patent" in v_low or "copyright" in v_low:
            return "Intellectual Property"
        if "terminat" in v_low or "durat" in v_low or "term" in v_low or "renew" in v_low:
            return "Termination"
        if "confident" in v_low or "priva" in v_low:
            return "Confidentiality"
        if "govern" in v_low or "law" in v_low or "jurisdict" in v_low or "dispute" in v_low:
            return "Governing Law"
        if "boiler" in v_low or "misc" in v_low or "sever" in v_low or "entire" in v_low:
            return "Boilerplate"
        return "Obligations"

    @field_validator("attention_level", mode="before")
    @classmethod
    def normalize_attention(cls, v: str) -> str:
        if not isinstance(v, str):
            return "standard"
        v_low = v.strip().lower()
        if "high" in v_low or "critical" in v_low or "severe" in v_low:
            return "high"
        if "mod" in v_low or "med" in v_low or "warn" in v_low:
            return "moderate"
        return "standard"


class LegalFinding(BaseModel):
    """
    Validated finding presented to the user.
    page_number, section_title, and verbatim_excerpt are hydrated directly from genuine DocumentChunks.
    LLM-generated verbatim quotes are NEVER trusted or displayed.
    """
    category: ClauseCategory = Field(..., description="Legal category of the clause")
    attention_level: AttentionLevel = Field(..., description="Assessed attention level (high, moderate, standard)")
    title: str = Field(..., description="Short descriptive heading for the finding")
    plain_english: str = Field(..., description="Clear explanation in plain English")
    why_it_matters: str = Field(..., description="Practical business or legal implication for the user")
    source_chunk_id: str = Field(..., description="Chunk ID reference")
    page_number: int = Field(..., description="1-indexed source page retrieved from genuine DocumentChunk")
    section_title: str = Field(..., description="Document section retrieved from genuine DocumentChunk")
    verbatim_excerpt: str = Field(..., description="Authentic extracted text retrieved from genuine DocumentChunk")
    citation_valid: bool = Field(True, description="Whether source_chunk_id was verified in the document")


class ExecutiveSummary(BaseModel):
    """High-level plain-language synthesis of the contract terms."""
    document_type: str = Field(..., description="Classified type of agreement, e.g. Master Services Agreement")
    parties: List[str] = Field(default_factory=list, description="Contracting parties identified in the text")
    effective_date: str = Field(..., description="Effective date or commencement timing")
    duration: str = Field(..., description="Term duration or renewal provisions")
    financial_summary: str = Field(..., description="Financial commitments, fees, or billing terms")
    high_level_overview: str = Field(..., description="Comprehensive 2-4 sentence overview of the agreement")


class CounselDiscussionPoint(BaseModel):
    """Actionable point prepared for attorney consultation."""
    clause_ref: str = Field(..., description="Clause or section identifier reference")
    topic: str = Field(..., description="Subject matter of concern")
    recommended_question: str = Field(..., description="Specific question to ask legal counsel")


class RawAnalysisOutput(BaseModel):
    """Raw structured output schema enforced on LLMs (Gemini / Grok)."""
    executive_summary: ExecutiveSummary = Field(..., description="Document overview and metadata synthesis")
    findings: List[RawFindingOutput] = Field(default_factory=list, description="Classified clause findings with chunk IDs")
    counsel_discussion_points: List[CounselDiscussionPoint] = Field(default_factory=list, description="Questions for attorney review")
    suggested_questions: List[str] = Field(default_factory=list, description="Suggested questions for document exploration")


class LegalAnalysis(BaseModel):
    """Common output contract returned by LegalAnalyzer with hydrated source citations."""
    executive_summary: ExecutiveSummary = Field(..., description="Document overview and metadata synthesis")
    findings: List[LegalFinding] = Field(default_factory=list, description="Validated clause findings with genuine chunk text")
    counsel_discussion_points: List[CounselDiscussionPoint] = Field(default_factory=list, description="Questions for attorney review")
    suggested_questions: List[str] = Field(default_factory=list, description="Suggested questions for document exploration")


class RawQAOutput(BaseModel):
    """Raw structured output from LLM for question answering."""
    answer: str = Field(..., description="Direct answer to the question")
    source_chunk_id: Optional[str] = Field(None, description="ID of chunk supporting the answer")


class QARequest(BaseModel):
    """Request payload for grounded contract Q&A."""
    question: str = Field(..., description="Natural language question about the document")


class QAResponse(BaseModel):
    """Grounded answer citing genuine document source."""
    question: str = Field(..., description="Original user question")
    answer: str = Field(..., description="Direct grounded answer")
    source_citation: str = Field(..., description="Citation string, e.g. 'Page 3 · Section 5.1'")
    page_number: int = Field(..., description="1-indexed source page")
    verbatim_excerpt: Optional[str] = Field(None, description="Authentic verbatim text from genuine DocumentChunk")
    source_chunk_id: Optional[str] = Field(None, description="Grounding chunk identifier")
